### ISSUE TITLE
squashmount.service systemd unit doesn't actually mount anything.

### ISSUE THREAD

**Issue by Astro-Johnny** [vaeth/squashmount#14]
Hello! Been using squashmount for some while (well, a long while) but stumbled on an issue. The provided systemd service starts and seems to be mounting things (or trying to) but the actual mountpoints don't actually get mounted. I.e., not shown when running `mount` and mount folder (here `/usr/portage`) is empty.

However, running `squashmount start` from command line seems to work fine. :confused: 

This is what I see in journal:
```
$ journalctl -b --unit squashmount
Aug 11 20:50:02 isg005 systemd[1]: Starting mount/umount all squashmount configured mount points...
Aug 11 20:50:03 isg005 squashmount[1698]:  * [portage]: mounting...
Aug 11 20:50:03 isg005 systemd[1]: Finished mount/umount all squashmount configured mount points.
Aug 11 20:53:52 isg005 systemd[1]: Stopping mount/umount all squashmount configured mount points...
Aug 11 20:53:52 isg005 squashmount[3576]:  * [portage]: squashing (this may take a while)
Aug 11 20:53:52 isg005 squashmount[3576]:  * [portage]: umounting...
Aug 11 20:53:52 isg005 squashmount[3598]: umount: /usr/portage: not mounted.
Aug 11 20:53:52 isg005 squashmount[3576]:  * [portage]: error:   non-lazy umount failed,
Aug 11 20:53:52 isg005 squashmount[3576]:                        using lazy umount of /usr/portage
Aug 11 20:53:52 isg005 squashmount[3599]: umount: /usr/portage: not mounted.
Aug 11 20:53:52 isg005 squashmount[3576]:  * [portage]: error:   lazy umount failed for /usr/portage
Aug 11 20:53:52 isg005 systemd[1]: squashmount.service: Deactivated successfully.
Aug 11 20:53:52 isg005 systemd[1]: Stopped mount/umount all squashmount configured mount points.
```

where service ran on startup, then I manually asked it to stop `systemctl stop squashmount`. Before running `squashmount start` manually, I use the force-forget escape hatch as it would otherwise say it's already mounted (when it isn't).

Using sys-fs/squashmount-22.1-r2 and sys-apps/systemd-255.7-r1 . I'm currently clueless why `squashmount start` should differ when run by service unit and when run manually on command line. Any ideas?

**Comment by vaeth** [comment]
I have not used systemd since several years. Probably, meanwhile some “security” features have been added to systemd which by default cause the mount to run only in some namespace only which is local to the process. I guess that systemd has some options to not use these namespaces. If there is a simple way to modify the squashmount.service unit to not use these namespaces, please let me know.

**Comment by Astro-Johnny** [comment]
Apparently it's as simple as adding
```
PrivateMounts=no
```
to `[Service]` section.

It took me _far_ too long to figure it out. It's because I used `systemctl show squashmount` to check the full applicable configuration. It _already_ said `PrivateMounts=no` so I kept overlooking it. But apparently `systemctl show` lies! :scream: You have to add it explicitly. (And systemd might need a bug report of its own.)

**Comment by Astro-Johnny** [comment]
Also, we're not the first to get bitten by this. https://unix.stackexchange.com/q/464959

**Comment by vaeth** [comment]
Thank you for spending the time to investigate this. I really do not have time these days. I will add the option to v22.2
