### ISSUE TITLE
Perl errors after first mount in 7.3

### ISSUE THREAD

**Issue by qsuscs** [vaeth/squashmount#3]
On starting by systemd or manually with `squashmount mount`, I get these errors: http://pastie.org/private/0gwf4sfdeq4uncphfkhva
Unfortunately, I know nothing at all about Perl, so I don’t know about any other log files I might provide; please ask as needed.
I downgraded to 6.3, which works without any errors.

**Comment by vaeth** [comment]
Since there is no further reply, I suppose that it is fixed now, so I am closing it.
Feel free to re-open (or open a new bug if necessary) if there is still something wrong.
