### ISSUE TITLE
Conflicts of squashmount and qt5 directory?

### ISSUE THREAD

**Issue by Petross404** [vaeth/squashmount#8]
Since I squashed `/usr/lib64/qt5` plasma panels and latte-doc started to malfunction and not be able to position correctly on screen.

Is it possible that squashmount removed some symlink or creating any problem?

**Comment by vaeth** [comment]
squashmount just mounts the partitions, so if at all, this is a problem of overlay or squashfs (or whatever the tools are which you use on your system).
There are some known problems especially with overlay but even more with unionfs-fuse and squashfuse if you should use the latter two.

However, the mentioned directory does not look problematic: I cannot see any hardlinks or other possibly dangerous stuff in it. Can you reproduce that it is the tools fault: If yes, unmounting the squashed directory and unsquashing the content of the produced squash file should make it work again.

**Comment by Petross404** [comment]
@vaeth I will test this tomorrow, thanks.

I will report back.

**Comment by Petross404** [comment]
Yes, it's not solved even after unsquashing `/usr/lib64/qt5` directory. Sorry to bother, feel free to close this issue as it has to be a coincidence that Plasma malfunctions since qt5 was squashed.
